" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

call plug#begin()
Plug 'vimwiki/vimwiki'
call plug#end()

let mapleader = ","

let g:vimwiki_list = [
    \{
    \   'path': '~/skrevolve.github.io/vimwiki/src/md',
    \   'syntax': 'markdown',
    \   'ext' : '.md',
    \   'diary_rel_path': '.',
    \}
\]

let g:vimwiki_conceallevel = 0

function! SaveAndConvertToHTML()
    write
    let current_file = expand('%:p')
    let relative_path = substitute(current_file, $HOME.'/skrevolve.github.io/vimwiki/src/md/', '', '')
    let html_file = $HOME.'/skrevolve.github.io/vimwiki/src/html/'.substitute(relative_path, '\.md$', '.html', '')
    let template_file = $HOME.'/skrevolve.github.io/vimwiki/src/html/template.html'
    
    silent !mkdir -p "$(dirname '".html_file."')"
    
    execute '!pandoc ' . current_file . 
           \ ' --template=' . template_file . 
           \ ' --metadata title="' . expand('%:t:r') . '"' .
           \ ' -s -o ' . html_file
endfunction

autocmd BufWritePost *.md call SaveAndConvertToHTML()

" command! WikiIndex :VimwikiIndex
" nmap <LocalLeader>ww <Plug>VimwikiIndex
" nmap <LocalLeader>wi <Plug>VimwikiDiaryIndex
" nmap <LocalLeader>w<LocalLeader>w <Plug>VimwikiMakeDiaryNote
" nmap <LocalLeader>wt :VimwikiTable<CR>